namespace: student-registration

backend:
  replicaCount: 1
  image:
    repository: anuragpatilcloud/student-registration-backend
    tag: ccbd3d93704e-14
    pullPolicy: IfNotPresent
  service:
    port: 8080

frontend:
  replicaCount: 1
  image:
    repository: anuragpatilcloud/student-registration-frontend
    tag: ccbd3d93704e-14
    pullPolicy: IfNotPresent
  service:
    port: 80

mariadb:
  image:
    repository: mariadb
    tag: ccbd3d93704e-14
    pullPolicy: IfNotPresent
  service:
    port: 3306
  database: student_registration
  username: Student
