apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-registration-mariadb
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-registration-mariadb
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-registration-mariadb
  template:
    metadata:
      labels:
        app: student-registration-mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: student-registration-mariadb
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: student-registration-mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: student-registration-mariadb
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: student-registration-mariadb
  ports:
    - name: mysql
      port: {{ .Values.mariadb.service.port }}
      targetPort: 3306
      protocol: TCP
